from collections.abc import Sequence
from datetime import datetime
from typing import Protocol

from sentinel.core.models import Device, Measurement, Outage, ScannedDevice, Scope, SpeedTest


class Prober(Protocol):
    def ping_many(self, targets: Sequence[str]) -> dict[str, float | None]: ...


class Scanner(Protocol):
    def scan(self) -> list[ScannedDevice]: ...


class SpeedTester(Protocol):
    def measure(self) -> tuple[float | None, float | None]: ...


class Notifier(Protocol):
    def notify(self, title: str, body: str) -> None: ...


class Store(Protocol):
    def add_measurement(self, measurement: Measurement) -> None: ...

    def recent_measurements(self, limit: int) -> list[Measurement]: ...

    def measurements_since(self, since: datetime) -> list[Measurement]: ...

    def open_outage(self) -> Outage | None: ...

    def start_outage(self, at: datetime, scope: Scope) -> None: ...

    def end_outage(self, at: datetime) -> None: ...

    def outages_since(self, since: datetime) -> list[Outage]: ...

    def devices(self) -> list[Device]: ...

    def record_scan(self, at: datetime, found: Sequence[ScannedDevice]) -> None: ...

    def last_scan_at(self) -> datetime | None: ...

    def set_nickname(self, mac: str, nickname: str) -> None: ...

    def prune(self, before: datetime) -> None: ...

    def add_speedtest(self, test: SpeedTest) -> None: ...

    def speedtests_since(self, since: datetime) -> list[SpeedTest]: ...

    def last_speedtest(self) -> SpeedTest | None: ...
